name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Git Identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Pull from Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://janya26:${HF_TOKEN}@huggingface.co/spaces/janya26/Proverb-Hub || true
          git fetch hf main
          git merge hf/main --allow-unrelated-histories -m "Merge Hugging Face space into GitHub repo"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://janya26:${HF_TOKEN}@huggingface.co/spaces/janya26/Proverb-Hub main
